### ISSUE TITLE
Multiple Attempts before showing Error data and Refresh option

### ISSUE THREAD

**Issue by dorjeys3** [Zen-Reportz/zen_dash#13]
Hello,

is there a way to increase the number of attempts to call the data before showing the "Copy Error and Refresh Data ". Seems like there is only 1 attempt and when i click refresh data then the data does show. So trying maybe 2 or 3 times before displaying the Error box would be great. 

thanks

**Comment by contactzen** [comment]
upgraded it with 0.4.2
