### ISSUE TITLE
Reactivity not working

### ISSUE THREAD

**Issue by dorjeys3** [Zen-Reportz/zen_dash#2]
Hello, 

Following is our code,  when we add reactivity , it is not working. 

`@app.post("/backend/filters/multi_date", response_model=i.ReturnData)
async def multi_date():
    first_date, last_date = default_date()
    first_date = first_date.isoformat()
    last_date = last_date.isoformat()

    return i.ReturnData(type=i.InstanceType.DATE, date_data=i.DateTimeData(label="Select Date Range",
                                                                           name="date",
                                                                           first_date=first_date,
                                                                           second_date=last_date),
                        flex=i.FlexData(fxFlex="18%"),         reactive=ReactiveData(ids=['Date Range Selection']),)
`

we want last and first date base upon other selection.

**Comment by contactzen** [comment]
fixed bug,

please use following code:

```
return i.ReturnData(type=i.InstanceType.DATE, date_data=i.DateTimeData(label="Select Date Range",
                                                                       name="date",
                                                                       first_date=first_date,
                                                                       second_date=last_date),
                    flex=i.FlexData(fxFlex="18%"),         reactive=ReactiveData(reactive_ids=['Date Range Selection']),)

```
