### ISSUE TITLE
Front End Error Notice

### ISSUE THREAD

**Issue by dorjeys3** [Zen-Reportz/zen_dash#38]
Hello,

Is there a way to create a Error notice for the front end users when an input is not of expected type/length?

**Comment by contactzen** [comment]
@dorjeys3 Can you please provide little more detail please ?

**Comment by dorjeys3** [comment]
Say I have an input box that will only take length of 4. If the user inserts more or less then 4 characters, then it should prompt the user with a message saying "input invalid, must be exactly 4 characters".

**Comment by contactzen** [comment]
Have you used json forms for this ?

**Comment by dorjeys3** [comment]
Thank you for the suggestion. I did use a json forms to resolve this issue. Now I need a way to provide a custom message with backend response when submit button is clicked. 

Thanks again.

**Comment by contactzen** [comment]
upgrade to 0.5.11. Ref: https://github.com/Zen-Reportz/zen_dash/blob/main/demo/pages/input_page/row_ten/__init__.py
