### ISSUE TITLE
Dynamic Change to File name

### ISSUE THREAD

**Issue by dorjeys3** [Zen-Reportz/zen_dash#4]
Hello,

```
@router.post("/download", response_model=i.ReturnData)
async def d3():
    return i.ReturnData(type=i.InstanceType.DOWNLOAD,
                        title="Download Results",
                        download_data=i.DownloadData(
                            file_name="output",
                            url="/backend/proactive/download_data"))

```                            
can we move the file_name from i.DownloadData to FileResponse(path=file_path, filename=file_path) ?
This way the file name can be changed dynamically. 

Thanks.

**Comment by contactzen** [comment]
Now, with 0.3.5 version you can do that. Please look at example https://github.com/Zen-Reportz/zen_dash/blob/main/demo/pages/page_one/row_seven.py
