### ISSUE TITLE
Custom Message with response when submit button is clicked in json forms

### ISSUE THREAD

**Issue by dorjeys3** [Zen-Reportz/zen_dash#49]
hello,

I want to pass custom message with response when the submit button is clicked in json forms. Can you also allow rending for custom duration? I want to keep the loading component for a longer duration with different custom messages. 

Thank you.

**Comment by contactzen** [comment]
upgrade to 0.5.11. Ref: https://github.com/Zen-Reportz/zen_dash/blob/main/demo/pages/input_page/row_ten/__init__.py
