### ISSUE TITLE
Floating Buttons on Page and global level

### ISSUE THREAD

**Issue by dorjeys3** [Zen-Reportz/zen_dash#50]
**Is your feature request related to a problem? Please describe.**
No. 

**Describe the solution you'd like**
Given a page, there is a floating BUTTON (possible locations top left, top right, middle left ,middle right, bottom left, bottom right) and multiple floating buttons can be added to a page. 

**Additional context**
Something like a next or previous button that you see in different mediums. 
This would be useful to have on both global and page level. 
Please also provide the option to add icons for these buttons. 

**Describe alternatives you've considered**
Using the current button option is an alternative but that takes up real estate and does not provides best user experience. 

Another option would be visibility dictated by the following code but only if backend allows for it. 
```
<button mat-fab color=“accent”>
  <mat-icon>add</mat-icon>
</button>

button[mat-fab] {
  position: fixed;
  right: 16px;
  bottom: 16px;
  z-index: 1000; // Ensure it floats above other content
}


```

**Comment by contactzen** [comment]
Added page level floting button, Upgrade to 0.6.3. Look at https://github.com/Zen-Reportz/zen_dash/blob/main/change.md

**Comment by dorjeys3** [comment]
hey thanks for working on this so quickly. 

Just wanted some clarification:

https://github.com/Zen-Reportz/zen_dash/blob/571f884645d6f982fb7bca3c32f35af081176402/zen_dash/objects/instances.py#L226

is this a typo (FEB vs FAB)?
https://material.angular.io/components/button/overview

**Comment by contactzen** [comment]
Thanks, I have fixed issue. Please let me know if you still see some naming issue. Upgrade to 0.6.5
