### ISSUE TITLE
Dynamic Sidebar rendering

### ISSUE THREAD

**Issue by dorjeys3** [Zen-Reportz/zen_dash#51]
Hello,

In the demo/example code that you provide, the sidebar group is still hard coded but the pages are dynamic. Is there a way to make the sidebar also dynamic. 

https://github.com/Zen-Reportz/zen_dash/blob/c4857f512154c049a26bbae9462abb789680504a/demo/main.py#L134

**Comment by contactzen** [comment]
Upgrade to 0.6.6
