### ISSUE TITLE
Pop up Display/Dialog Box for return updatedata

### ISSUE THREAD

**Issue by dorjeys3** [Zen-Reportz/zen_dash#52]
Hello,

I like the current display but its really small and eventually it disappears.
Can we have the option to display the returned updatedate in the middle and requires manual close to acknowledge the message. 

If possible, I would like more control on the returned updatedata for displaying. Maybe a custom HTML Where i can add buttons?

**Comment by contactzen** [comment]
upgrade to 0.6.7
