### ISSUE TITLE
HighChartType.MAP Bug

### ISSUE THREAD

**Issue by dorjeys3** [Zen-Reportz/zen_dash#53]
hello,

Seems like the code for HighChart Map is incomplete.

https://github.com/Zen-Reportz/zen_dash/blob/156db42302d88402fb5d48115201d7a066094b8c/frontend/src/app/component/highchart/highchart.component.ts#L1

**Comment by contactzen** [comment]
Thank you . Upgrade to 0.6.10 , example provided for detail check change.md
