### ISSUE TITLE
Issue with Submit/Refresh button

### ISSUE THREAD

**Issue by dorjeys3** [Zen-Reportz/zen_dash#54]
Hello,

I believe at previously there was a fix with the submit/refresh button where it would cancel all the api calls to apply the new filters/changes and make the api calls for the new filters. 

However, there seems to be an issue with api calls that take a bit longer (10s or more from what I am seeing). It fails to cancel these calls. Therefore the values displayed in the different boxes are mixed between the previous calls that did not get cancelled and the new api calls (the ones that did manage to get cancelled and new api calls were made).

**Comment by contactzen** [comment]
You are taking about canceling request when in mid flight before seeing data, I have added that feature in  0.6.11

**Comment by dorjeys3** [comment]
Hello,

I am noticing that switching between tabs is not canceling the API calls. I believe the issue was initially fixed as 0.6.11 however, somewhere in between, it seems to have stopped working.
