### ISSUE TITLE
Issues with Date Reactivity In Sidebar

### ISSUE THREAD

**Issue by dorjeys3** [Zen-Reportz/zen_dash#55]
I am experiencing issues with reactivity in the sidebar. For some reason, the reactivity only works on page_0 and fails to react in all other pages. 

 I believe the issue maybe in APIcallservice.ts line 30 (https://github.com/Zen-Reportz/zen_dash/blob/366fa09487e1fb54888f81f5171ce1e612a0cff8/frontend/src/app/services/api-call.service.ts#L30C46-L30C46), where it needs to include all of the input_types from line 13 (https://github.com/Zen-Reportz/zen_dash/blob/366fa09487e1fb54888f81f5171ce1e612a0cff8/frontend/src/app/services/api-call.service.ts#L13)

Thank you.

**Comment by dorjeys3** [comment]
Actually the issue seems to be at https://github.com/Zen-Reportz/zen_dash/blob/366fa09487e1fb54888f81f5171ce1e612a0cff8/frontend/src/app/services/api-call.service.ts#L190

**Comment by contactzen** [comment]
You are correct, I have fixed and upgrade to 0.6.12
