### ISSUE TITLE
Issues with Date/Multidate

### ISSUE THREAD

**Issue by dorjeys3** [Zen-Reportz/zen_dash#56]
Hello,

There seems to be an issue with the way the date appears in the date input box. 

Here is an example: 
Line 27 date values do not match the front end date values. Its off by a day. 

https://github.com/Zen-Reportz/zen_dash/blob/81ba2ccfee4781f3b2d75228999e568b34a9991e/demo/pages/input_page/row_one/view.py#L27

![image](https://github.com/Zen-Reportz/zen_dash/assets/60681172/62b30b74-fe5d-4123-9cb6-872e26897c42)

**Comment by contactzen** [comment]
I have fixed issue, check change.md for detail . Upgrade it to 0.6.13
