### ISSUE TITLE
Highchart Legend Not Showing

### ISSUE THREAD

**Issue by dorjeys3** [Zen-Reportz/zen_dash#57]
Hello, 

HighchartType.Stock does not show legend. 

I tried this in JsFiddle and it works but doesnt work in ZenDash. 

Here is an example:
https://jsfiddle.net/5v1xod90/

`Highcharts.chart('container', {
    "rangeSelector":
    {
        "selected": 1
    },
    "xAxis":
    {
        "title":
        {
            "text": "Attack time"
        }
    },
    "series":
    [
        {
            "name": "Swing",
            "data":
            [
                [
                    1588204800000.0,
                    2.0
                ],
                [
                    1588291200000.0,
                    1.0
                ],
                [
                    1588377600000.0,
                    1.0
                ],
                [
                    1588464000000.0,
                    0.0
                ],
                [
                    1588550400000.0,
                    1.0
                ]
            ]
        },
        {
            "name": "Knee",
            "data":
            [
                [
                    1588204800000.0,
                    0.0
                ],
                [
                    1588291200000.0,
                    0.0
                ],
                [
                    1588377600000.0,
                    0.0
                ],
                [
                    1588464000000.0,
                    0.0
                ],
                [
                    1588550400000.0,
                    0.0
                ]
            ]
        },
        {
            "name": "Elbow",
            "data":
            [
                [
                    1588204800000.0,
                    0.0
                ],
                [
                    1588291200000.0,
                    0.0
                ],
                [
                    1588377600000.0,
                    0.0
                ],
                [
                    1588464000000.0,
                    0.0
                ],
                [
                    1588550400000.0,
                    0.0
                ]
            ]
        },
        {
            "name": "Kick",
            "data":
            [
                [
                    1588204800000.0,
                    0.0
                ],
                [
                    1588291200000.0,
                    0.0
                ],
                [
                    1588377600000.0,
                    0.0
                ],
                [
                    1588464000000.0,
                    0.0
                ],
                [
                    1588550400000.0,
                    0.0
                ]
            ]
        },
        {
            "name": "Punch",
            "data":
            [
                [
                    1588204800000.0,
                    0.0
                ],
                [
                    1588291200000.0,
                    0.0
                ],
                [
                    1588377600000.0,
                    0.0
                ],
                [
                    1588464000000.0,
                    0.0
                ],
                [
                    1588550400000.0,
                    0.0
                ]
            ]
        },
        {
            "name": "Bite",
            "data":
            [
                [
                    1588204800000.0,
                    0.0
                ],
                [
                    1588291200000.0,
                    1.0
                ],
                [
                    1588377600000.0,
                    2.0
                ],
                [
                    1588464000000.0,
                    0.0
                ],
                [
                    1588550400000.0,
                    2.0
                ]
            ]
        }
    ],
    "title":
    {
        "text": "Attack Chart"
    },
    "yAxis":
    {
        "title":
        {
            "text": "Attacks"
        }
    },
    "legend":
    {
        "layout": "horizontal",
        "align": "center",
        "verticalAlign": "bottom"
    },
    "tooltip":
    {
        "shared": true,
        "split": false,
        "valueDecimals": 0
    },
    
});
`

**Comment by contactzen** [comment]
For highchart stock, legend is not enabled by default. You need to enable it by providing following

    "legend":
    {
        "layout": "horizontal",
        "align": "center",
        "verticalAlign": "bottom",
        "enabled": True
    },
