### ISSUE TITLE
Rendering of a Page is currently dependent on the sidebar order

### ISSUE THREAD

**Issue by dorjeys3** [Zen-Reportz/zen_dash#60]
I want this feature to be more flexible. 

For example, I don't want to show the "Charts" subtab as an option in the sidebar. I want this page to be rendered when the custom URL is triggered or when the tab_number and subtab_number match.

[def RenderTabs(sidebar_list: SidebarList):](https://github.com/Zen-Reportz/zen_dash/blob/2912b3c463f7010ec49bed05ff376f125299de2b/zen_dash/objects/sidebar.py#L66)

**Comment by contactzen** [comment]
upgrade to 0.6.25
