### ISSUE TITLE
API calls are not being cancelled when switching tabs.

### ISSUE THREAD

**Issue by dorjeys3** [Zen-Reportz/zen_dash#61]
Hello,

I am noticing that switching between tabs is not canceling the API calls. I believe the issue was initially fixed as 0.6.11 however, somewhere in between, it seems to have stopped working.

_Originally posted by @dorjeys3 in https://github.com/Zen-Reportz/zen_dash/issues/54#issuecomment-2161247626_

**Comment by contactzen** [comment]
which version of zen_dash are you using ?

**Comment by contactzen** [comment]
closing issue since I dont know which version you are using. If you have still issue, please open again with version detail
