### ISSUE TITLE
Download file name appears weird

### ISSUE THREAD

**Issue by dorjeys3** [Zen-Reportz/zen_dash#7]
Prior to 3.5 update, I was able to download files with proper extension and whatever was added into the DownloadData(file_name). 
Now the file names consist of `utf-8"` in the beginning. Ex: `utf-8''20221110-14%3A55%3A34_output.xlsx`

```
file = datetime.now().strftime("%Y%m%d-%H:%M:%S_") + "output.xlsx"
df.to_excel(f"files/{file}")
file_path = f"files/{file}"
return FileResponse(path=file_path, filename=file)
```

**Comment by contactzen** [comment]
updated functionality with 0.3.6 version
